# Generated by Django 2.1 on 2018-09-28 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0003_auto_20180928_2053'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='Productos',
        ),
    ]
