# Generated by Django 2.1 on 2018-09-29 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0004_auto_20180928_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='question',
            new_name='categoria',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='choice_text',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='votes',
        ),
        migrations.AddField(
            model_name='productos',
            name='carateristicas',
            field=models.CharField(default=-3.0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productos',
            name='descripcion',
            field=models.CharField(default=-3.0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productos',
            name='nombre_producto',
            field=models.CharField(default=-3.0, max_length=100),
            preserve_default=False,
        ),
    ]
