# Generated by Django 2.1 on 2018-09-29 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0006_auto_20180928_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='carateristicas',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='productos',
            name='descripcion',
            field=models.TextField(max_length=500),
        ),
    ]
