# Generated by Django 2.1 on 2018-09-29 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0008_auto_20180928_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='model_pic',
            field=models.ImageField(default=-3.0, upload_to=''),
            preserve_default=False,
        ),
    ]
