# Generated by Django 2.1 on 2018-09-29 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0009_productos_model_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=1000)),
                ('carateristicas', models.TextField(max_length=1000)),
                ('model_pic', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='productos',
            name='categoria',
        ),
        migrations.RenameModel(
            old_name='Categorias',
            new_name='Categoria',
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.Categoria'),
        ),
    ]
