# Generated by Django 2.1 on 2018-09-29 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0012_auto_20180928_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='backoffice/static/images/'),
        ),
    ]
