# Generated by Django 2.1 on 2018-10-03 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0015_auto_20180929_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='imagen',
            field=models.FileField(upload_to=''),
        ),
    ]
