# Generated by Django 2.1 on 2018-10-03 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0016_auto_20181002_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='imagen',
            field=models.FileField(upload_to='categorias/'),
        ),
    ]
