# Generated by Django 2.1 on 2018-10-04 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0018_auto_20181002_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='visitas',
            field=models.IntegerField(default=0),
        ),
    ]
